language: c
git:
   submodules: false
env:
  global:
    - LC_ALL=C
  matrix:
    - IMAGE=debian-amd64
      TARGET_LIST=x86_64-softmmu,x86_64-linux-user
    - IMAGE=debian-mips-cross
      TARGET_LIST=mips-softmmu
build:
  pre_ci_boot:
    image_name: registry.gitlab.com/qemu-project/qemu/qemu/${IMAGE}
    image_tag: latest
    pull: true
    options: "-e HOME=/root"
  ci:
    - unset CC
    - mkdir build
    - cd build
    - ../configure --disable-docs ${QEMU_CONFIGURE_OPTS} --target-list=${TARGET_LIST}
    - make -j$(($(getconf _NPROCESSORS_ONLN) + 1))
