/* prjComps.h - dynamically generated configuration header */


/*
GENERATED: Thu Aug 04 12:09:57 +0200 2011
DO NOT EDIT - file is regenerated whenever the project changes
*/

#ifndef INCprjCompsh
#define INCprjCompsh

/*** INCLUDED COMPONENTS ***/

#define INCLUDE_ARINC_SCHEDULER_INIT
#define INCLUDE_ARP_API
#define INCLUDE_AUX_CLK
#define INCLUDE_BOOT_LINE
#define INCLUDE_BOOT_LINE_INIT
#define INCLUDE_BRANCH_PREDICTION
#define INCLUDE_BSD_SOCKET
#define INCLUDE_BSP_MODULES
#define INCLUDE_BSP_VXWORKS
#define INCLUDE_CPM
#define INCLUDE_DEBUG_CORE
#define INCLUDE_DUART
#define INCLUDE_DUART_EXT
#define INCLUDE_E500_FIT
#define INCLUDE_END
#define INCLUDE_END_BOOT
#define INCLUDE_EPIC
#define INCLUDE_FTP
#define INCLUDE_HOST_TBL
#define INCLUDE_ICMP
#define INCLUDE_IGMP
#define INCLUDE_IO_EXTRA_INIT
#define INCLUDE_IO_SYSTEM_INIT
#define INCLUDE_IP
#define INCLUDE_KERNEL_BASIC
#define INCLUDE_KERNEL_BASIC_INIT
#define INCLUDE_KERNEL_BASIC_INIT2
#define INCLUDE_KERNEL_CORE
#define INCLUDE_KERNEL_FULL
#define INCLUDE_KERNEL_NORMAL_MODE
#define INCLUDE_L2_CACHE
#define INCLUDE_L2_SRAM
#define INCLUDE_LOCAL_SDRAM
#define INCLUDE_LOOPBACK
#define INCLUDE_M85XX_TIMER
#define INCLUDE_MIILIB
#define INCLUDE_MOT_TSEC_END
#define INCLUDE_MUX
#define INCLUDE_NETDEV_CONFIG
#define INCLUDE_NETDEV_NAMEGET
#define INCLUDE_NETINET_IF
#define INCLUDE_NETINET_IF_ETHER
#define INCLUDE_NETINET_IF_SUBR
#define INCLUDE_NETINET_IGMP
#define INCLUDE_NETINET_IN
#define INCLUDE_NETINET_IN_CKSUM
#define INCLUDE_NETINET_IN_PCB
#define INCLUDE_NETINET_IN_PROTO
#define INCLUDE_NETINET_IP_ICMP
#define INCLUDE_NETINET_IP_INPUT
#define INCLUDE_NETINET_IP_OUTPUT
#define INCLUDE_NETINET_RADIX
#define INCLUDE_NETINET_RAW_IP
#define INCLUDE_NETINET_ROUTE
#define INCLUDE_NETINET_SYS_SOCKET
#define INCLUDE_NETINET_UDP_USRREQ
#define INCLUDE_NETINET_UIPC_DOM
#define INCLUDE_NETINET_UIPC_MBUF
#define INCLUDE_NETINET_UIPC_SOCK
#define INCLUDE_NETINET_UIPC_SOCK2
#define INCLUDE_NETINET_UNIXLIB
#define INCLUDE_NETMASK_GET
#define INCLUDE_NETWORK
#define INCLUDE_NETWRS_ETHERMULTILIB
#define INCLUDE_NETWRS_IFLIB
#define INCLUDE_NETWRS_INETLIB
#define INCLUDE_NETWRS_NETBUFLIB
#define INCLUDE_NETWRS_REMLIB
#define INCLUDE_NETWRS_ROUTELIB
#define INCLUDE_NETWRS_XDR
#define INCLUDE_NET_DRV
#define INCLUDE_NET_HOST_SETUP
#define INCLUDE_NET_INIT
#define INCLUDE_NET_LIB
#define INCLUDE_NET_RANDOM
#define INCLUDE_NET_REM_IO
#define INCLUDE_NET_SETUP
#define INCLUDE_NET_TASK
#define INCLUDE_NS16550SIO
#define INCLUDE_NV_RAM
#define INCLUDE_PARTITION_INIT
#define INCLUDE_POST_KERNEL_CORE_INIT
#define INCLUDE_POST_KERNEL_CORE_INIT2
#define INCLUDE_PPCDECTIMER
#define INCLUDE_PRE_KERNEL_CORE_INIT
#define INCLUDE_PRIMARY_TSEC_END
#define INCLUDE_SECONDARY_TSEC_END
#define INCLUDE_SERIAL
#define INCLUDE_SPE
#define INCLUDE_SYSTEM_START_INIT
#define INCLUDE_TCP
#define INCLUDE_TFTP_CLIENT
#define INCLUDE_TIMESTAMP
#define INCLUDE_TIME_MONITOR_INIT
#define INCLUDE_TTY_DEV
#define INCLUDE_UDP
#define INCLUDE_USER_APPL
#define INCLUDE_USR_DEVSPLIT
#define INCLUDE_USR_FLASH
#define INCLUDE_WDB
#define INCLUDE_WDB_COMM_END

#endif /* INCprjCompsh */
