/* prjParams.h - dynamically generated configuration header */


/*
GENERATED: Thu Aug 04 12:09:57 +0200 2011
DO NOT EDIT - file is regenerated whenever the project changes
*/

#ifndef INCprjParamsh
#define INCprjParamsh


/*** INCLUDED COMPONENTS ***/

#define INCLUDE_ARINC_SCHEDULER_INIT
#define INCLUDE_ARP_API
#define INCLUDE_AUX_CLK
#define INCLUDE_BOOT_LINE
#define INCLUDE_BOOT_LINE_INIT
#define INCLUDE_BRANCH_PREDICTION
#define INCLUDE_BSD_SOCKET
#define INCLUDE_BSP_MODULES
#define INCLUDE_BSP_VXWORKS
#define INCLUDE_CPM
#define INCLUDE_DEBUG_CORE
#define INCLUDE_DUART
#define INCLUDE_DUART_EXT
#define INCLUDE_E500_FIT
#define INCLUDE_END
#define INCLUDE_END_BOOT
#define INCLUDE_EPIC
#define INCLUDE_FTP
#define INCLUDE_HOST_TBL
#define INCLUDE_ICMP
#define INCLUDE_IGMP
#define INCLUDE_IO_EXTRA_INIT
#define INCLUDE_IO_SYSTEM_INIT
#define INCLUDE_IP
#define INCLUDE_KERNEL_BASIC
#define INCLUDE_KERNEL_BASIC_INIT
#define INCLUDE_KERNEL_BASIC_INIT2
#define INCLUDE_KERNEL_CORE
#define INCLUDE_KERNEL_FULL
#define INCLUDE_KERNEL_NORMAL_MODE
#define INCLUDE_L2_CACHE
#define INCLUDE_L2_SRAM
#define INCLUDE_LOCAL_SDRAM
#define INCLUDE_LOOPBACK
#define INCLUDE_M85XX_TIMER
#define INCLUDE_MIILIB
#define INCLUDE_MOT_TSEC_END
#define INCLUDE_MUX
#define INCLUDE_NETDEV_CONFIG
#define INCLUDE_NETDEV_NAMEGET
#define INCLUDE_NETINET_IF
#define INCLUDE_NETINET_IF_ETHER
#define INCLUDE_NETINET_IF_SUBR
#define INCLUDE_NETINET_IGMP
#define INCLUDE_NETINET_IN
#define INCLUDE_NETINET_IN_CKSUM
#define INCLUDE_NETINET_IN_PCB
#define INCLUDE_NETINET_IN_PROTO
#define INCLUDE_NETINET_IP_ICMP
#define INCLUDE_NETINET_IP_INPUT
#define INCLUDE_NETINET_IP_OUTPUT
#define INCLUDE_NETINET_RADIX
#define INCLUDE_NETINET_RAW_IP
#define INCLUDE_NETINET_ROUTE
#define INCLUDE_NETINET_SYS_SOCKET
#define INCLUDE_NETINET_UDP_USRREQ
#define INCLUDE_NETINET_UIPC_DOM
#define INCLUDE_NETINET_UIPC_MBUF
#define INCLUDE_NETINET_UIPC_SOCK
#define INCLUDE_NETINET_UIPC_SOCK2
#define INCLUDE_NETINET_UNIXLIB
#define INCLUDE_NETMASK_GET
#define INCLUDE_NETWORK
#define INCLUDE_NETWRS_ETHERMULTILIB
#define INCLUDE_NETWRS_IFLIB
#define INCLUDE_NETWRS_INETLIB
#define INCLUDE_NETWRS_NETBUFLIB
#define INCLUDE_NETWRS_REMLIB
#define INCLUDE_NETWRS_ROUTELIB
#define INCLUDE_NETWRS_XDR
#define INCLUDE_NET_DRV
#define INCLUDE_NET_HOST_SETUP
#define INCLUDE_NET_INIT
#define INCLUDE_NET_LIB
#define INCLUDE_NET_RANDOM
#define INCLUDE_NET_REM_IO
#define INCLUDE_NET_SETUP
#define INCLUDE_NET_TASK
#define INCLUDE_NS16550SIO
#define INCLUDE_NV_RAM
#define INCLUDE_PARTITION_INIT
#define INCLUDE_POST_KERNEL_CORE_INIT
#define INCLUDE_POST_KERNEL_CORE_INIT2
#define INCLUDE_PPCDECTIMER
#define INCLUDE_PRE_KERNEL_CORE_INIT
#define INCLUDE_PRIMARY_TSEC_END
#define INCLUDE_SECONDARY_TSEC_END
#define INCLUDE_SERIAL
#define INCLUDE_SPE
#define INCLUDE_SYSTEM_START_INIT
#define INCLUDE_TCP
#define INCLUDE_TFTP_CLIENT
#define INCLUDE_TIMESTAMP
#define INCLUDE_TIME_MONITOR_INIT
#define INCLUDE_TTY_DEV
#define INCLUDE_UDP
#define INCLUDE_USER_APPL
#define INCLUDE_USR_DEVSPLIT
#define INCLUDE_USR_FLASH
#define INCLUDE_WDB
#define INCLUDE_WDB_COMM_END
#undef INCLUDE_ACE
#undef INCLUDE_ATA
#undef INCLUDE_CBIO_MAIN
#undef INCLUDE_CBIO_DCACHE
#undef INCLUDE_CBIO_DPART
#undef INCLUDE_ATA_SHOW
#undef INCLUDE_BOOT_APP
#undef INCLUDE_BOOT_LOADER
#undef INCLUDE_BOOTP
#undef INCLUDE_BPF
#undef INCLUDE_BSD
#undef BSD43_COMPATIBLE
#undef INCLUDE_BSD_BOOT
#undef INCLUDE_CBIO_RAMDISK
#undef INCLUDE_DOSFS
#undef INCLUDE_RAWFS
#undef INCLUDE_CDROMFS
#undef INCLUDE_DEBUG_TOOL
#undef INCLUDE_SHELL
#undef INCLUDE_DEBUG_UTIL
#undef INCLUDE_DEFER_NET_INIT
#undef INCLUDE_DHCP_CORE
#undef INCLUDE_DHCPC
#undef INCLUDE_ROUTE_SOCK
#undef INCLUDE_DHCPC_LEASE_CLEAN
#undef INCLUDE_DHCPC_LEASE_GET
#undef INCLUDE_DHCPC_SHARE
#undef INCLUDE_DHCPC_SHOW
#undef INCLUDE_DHCPR
#undef INCLUDE_DHCPS
#undef INCLUDE_DHCPS_SHARE
#undef INCLUDE_DNS_RESOLVER
#undef INCLUDE_FTP_SERVER
#undef INCLUDE_FTPD_SECURITY
#undef INCLUDE_SECURITY
#undef INCLUDE_ICMP_SHOW
#undef INCLUDE_IF_USR
#undef INCLUDE_IGMP_SHOW
#undef INCLUDE_IP_FILTER
#undef INCLUDE_KERNEL_SHOW
#undef INCLUDE_EXC_SHOW_INIT
#undef INCLUDE_KERNEL_UTIL
#undef INCLUDE_LOADER
#undef INCLUDE_LOADER_EXTRA
#undef INCLUDE_LOGIN
#undef INCLUDE_LPT
#undef INCLUDE_MAL_FTP
#undef INCLUDE_MAL_HTTP
#undef INCLUDE_MAL_TFTP
#undef INCLUDE_MCAST_ROUTING
#undef INCLUDE_MEMDRV
#undef INCLUDE_MIB2_ALL
#undef INCLUDE_MIB2_AT
#undef INCLUDE_MIB2_ICMP
#undef INCLUDE_MIB2_IF
#undef INCLUDE_MIB2_IP
#undef INCLUDE_MIB2_RIP
#undef INCLUDE_RIP
#undef INCLUDE_MIB2_SYSTEM
#undef INCLUDE_MIB2_TCP
#undef INCLUDE_MIB2_UDP
#undef INCLUDE_NET_SHOW
#undef INCLUDE_NET_SYM_TBL
#undef INCLUDE_NETINET_IP_MROUTE
#undef INCLUDE_NETINET_RAW_CB
#undef INCLUDE_NETINET_RAW_USRREQ
#undef INCLUDE_NETINET_RTSOCK
#undef INCLUDE_NETINET_SL_COMPRESS
#undef INCLUDE_NETWRS_MBUFLIB
#undef INCLUDE_NETWRS_MBUFSOCKLIB
#undef INCLUDE_NETWRS_NFSHASH
#undef INCLUDE_NETWRS_XDR_BOOL_T
#undef INCLUDE_NETWRS_XDR_NFS
#undef INCLUDE_NETWRS_XDR_NFSSERV
#undef INCLUDE_NFS
#undef INCLUDE_RPC
#undef INCLUDE_NFS_MOUNT_ALL
#undef INCLUDE_NFS_SERVER
#undef INCLUDE_OS_UNIXDRV
#undef INCLUDE_PARTITION_TOOL
#undef INCLUDE_PC_CONSOLE
#undef INCLUDE_DRV_PCCONSOLE
#undef INCLUDE_M6845VGA
#undef INCLUDE_PCI_PARAMS
#undef INCLUDE_PCMCIA
#undef INCLUDE_PING
#undef INCLUDE_POSIX
#undef INCLUDE_POSIX_SHOW
#undef INCLUDE_PPP
#undef INCLUDE_PPP_OPTIONS
#undef INCLUDE_PPP_BOOT
#undef INCLUDE_PPP_CRYPT
#undef INCLUDE_PROXY_CLIENT
#undef INCLUDE_PROXY_SERVER
#undef INCLUDE_RBUFF
#undef INCLUDE_WINDVIEW
#undef INCLUDE_RBUFF_SHOW
#undef INCLUDE_RLOGIN
#undef INCLUDE_SCSI
#undef INCLUDE_SECURE_SHELL
#undef INCLUDE_SEQ_TIMESTAMP
#undef INCLUDE_SYM_TBL_INIT
#undef INCLUDE_SHELL_EMACS_MODE
#undef INCLUDE_SHELL_REMOTE
#undef INCLUDE_SHELL_VI_MODE
#undef INCLUDE_SLIP
#undef INCLUDE_SLIP_BOOT
#undef INCLUDE_SM_COMMON
#undef INCLUDE_SM_OBJ_COMMON
#undef INCLUDE_SNTPC
#undef INCLUDE_SNTPS
#undef INCLUDE_STANDALONE_SYM_TBL
#undef INCLUDE_SYS_TIMESTAMP
#undef INCLUDE_TCP_DEBUG
#undef INCLUDE_TCP_SHOW
#undef INCLUDE_TELNET
#undef INCLUDE_TFTP_SERVER
#undef INCLUDE_UDP_SHOW
#undef INCLUDE_USER_TIMESTAMP
#undef INCLUDE_USER_ENTRIES
#undef INCLUDE_USR_FS_UTILS
#undef INCLUDE_TAR
#undef INCLUDE_VME_PARAMS
#undef INCLUDE_WDB_COMM_MINI_UDP
#undef INCLUDE_WDB_COMM_NETWORK
#undef INCLUDE_WDB_COMM_PIPE
#undef INCLUDE_WDB_COMM_SERIAL
#undef INCLUDE_WDB_TRG
#undef INCLUDE_WV_BUFF_USER
#undef INCLUDE_WVUPLOAD_FILE
#undef INCLUDE_WVUPLOAD_SOCK
#undef INCLUDE_WVUPLOAD_TSFSSOCK
#undef INCLUDE_ZBUF_SOCK
#undef INCLUDE_FD
#undef INCLUDE_AMIO_REDIRECT
#undef INCLUDE_PAYLOAD_CKSUM
#undef INCLUDE_SPE_SHOW
#undef INCLUDE_SECOND_SMEND_BOOT
#undef INCLUDE_SMEND_SHOW
#undef INCLUDE_DHCPC_LEASE_SAVE
#undef INCLUDE_SMEND_ADDRGET
#undef INCLUDE_I8048KBD
#undef INCLUDE_I8042KBD
#undef INCLUDE_T2_BOOT_LOADER
#undef INCLUDE_DHCPC_BOOT
#undef INCLUDE_AIC7880_SCSI
#undef INCLUDE_AMBAINTRCTL
#undef INCLUDE_AMBASIO
#undef INCLUDE_AMBATIMER
#undef INCLUDE_BYTENVRAM
#undef INCLUDE_CD2400SIO
#undef INCLUDE_CIOTIMER
#undef INCLUDE_CTB69000VGA
#undef INCLUDE_DEC21X40END
#undef INCLUDE_DEC21X4XEND
#undef INCLUDE_EI82596END
#undef INCLUDE_EI82596HKVEND
#undef INCLUDE_EL3C90XEND
#undef INCLUDE_ELT3C509END
#undef INCLUDE_EV960JXTIMER
#undef INCLUDE_EVBNS16550SIO
#undef INCLUDE_NEC765FD
#undef INCLUDE_FEI82557END
#undef INCLUDE_FLASHMEM
#undef INCLUDE_GEI8254X_END
#undef INCLUDE_I82378IBC
#undef INCLUDE_I8237DMA
#undef INCLUDE_L64853DMA
#undef INCLUDE_I8250SIO
#undef INCLUDE_I8253TIMER
#undef INCLUDE_I8254TIMER
#undef INCLUDE_I8259INTR
#undef INCLUDE_I8259PIC
#undef INCLUDE_IFLASHMEM
#undef INCLUDE_IOAPICINTR
#undef INCLUDE_IOLICOMEND
#undef INCLUDE_IPIIX4PCI
#undef INCLUDE_LN7990END
#undef INCLUDE_LN97XEND
#undef INCLUDE_LOAPICINTR
#undef INCLUDE_LOAPICTIMER
#undef INCLUDE_LR33KTIMER
#undef INCLUDE_LR4102TIMER
#undef INCLUDE_M48T18NVRAM
#undef INCLUDE_M68230TIMER
#undef INCLUDE_M68302SIO
#undef INCLUDE_M68302TIMER
#undef INCLUDE_M68332SIO
#undef INCLUDE_M68332TIMER
#undef INCLUDE_M68340SERIAL
#undef INCLUDE_M68340TIMER
#undef INCLUDE_M68360SIO
#undef INCLUDE_M68360TIMER
#undef INCLUDE_M68562SIO
#undef INCLUDE_M68562TIMER
#undef INCLUDE_M68681SERIAL
#undef INCLUDE_M68681SIO
#undef INCLUDE_M68681TIMER
#undef INCLUDE_M68901SIO
#undef INCLUDE_M68901TIMER
#undef INCLUDE_M8260FLASH
#undef INCLUDE_M8260INTRCTL
#undef INCLUDE_M8260SIO
#undef INCLUDE_M8260TIMER
#undef INCLUDE_MB86940SIO
#undef INCLUDE_MB86940TIMER
#undef INCLUDE_MB86960END
#undef INCLUDE_MB87030_SCSI
#undef INCLUDE_MBCEND
#undef INCLUDE_MCCTIMER
#undef INCLUDE_MIPSR4KTIMER
#undef INCLUDE_MIPSR4KTIMER_AUXCLK
#undef INCLUDE_MOTTSECEND
#undef INCLUDE_MOTCPMEND
#undef INCLUDE_MOTFCCEND
#undef INCLUDE_MOTFECEND
#undef INCLUDE_N72001SERIAL
#undef INCLUDE_N72001SIO
#undef INCLUDE_N8571RTC
#undef INCLUDE_N8571TIMER
#undef INCLUDE_NCR5390_SCSI1
#undef INCLUDE_NCR5390_SCSI2
#undef INCLUDE_NCR710_SCSI1
#undef INCLUDE_NCR710_SCSI2
#undef INCLUDE_NCR810_SCSI
#undef INCLUDE_NCR89105TIMER
#undef INCLUDE_NE2000END
#undef INCLUDE_NICEVBEND
#undef INCLUDE_NTEND
#undef INCLUDE_NULLVME
#undef INCLUDE_NULLNVRAM
#undef INCLUDE_NVRAM
#undef INCLUDE_NVRAMTOFLASH
#undef INCLUDE_PCC2TIMER
#undef INCLUDE_PCCTIMER
#undef INCLUDE_PCI_CFG_LIB
#undef INCLUDE_PCI_CFG_MECH0
#undef INCLUDE_PCI_CFG_MECH1
#undef INCLUDE_PCI_CFG_MECH2
#undef INCLUDE_PCI_CFGSHOW
#undef INCLUDE_PCI_INT
#undef INCLUDE_PCI_AUTOCFG
#undef INCLUDE_PPC401INTR
#undef INCLUDE_PPC403INTR
#undef INCLUDE_PPC403SIO
#undef INCLUDE_PPC403TIMER
#undef INCLUDE_PPC860INTR
#undef INCLUDE_PPC860SIO
#undef INCLUDE_PPC860TIMER
#undef INCLUDE_PPCZ8536TIMER
#undef INCLUDE_PS2DMA
#undef INCLUDE_PS2FD
#undef INCLUDE_SA1100INTRCTL
#undef INCLUDE_SA1100SIO
#undef INCLUDE_SA1100TIMER
#undef INCLUDE_SA1501TIMER
#undef INCLUDE_SA150XINTRCTL
#undef INCLUDE_SMCFDC37B78X
#undef INCLUDE_SN83932END
#undef INCLUDE_SONICTIMER
#undef INCLUDE_ST16552SIO
#undef INCLUDE_SUN4TIMER
#undef INCLUDE_SUNECTIMER
#undef INCLUDE_SWTIMER
#undef INCLUDE_SYM895_SCSI
#undef INCLUDE_TEMPLATE_END
#undef INCLUDE_TEMPLATE_INTRCTL
#undef INCLUDE_TEMPLATE_NVRAM
#undef INCLUDE_TEMPLATE_SCSI2
#undef INCLUDE_TEMPLATE_SIO
#undef INCLUDE_TEMPLATE_TIMER
#undef INCLUDE_TEMPLATE_VME
#undef INCLUDE_ULTRAEND
#undef INCLUDE_UNIXSERIAL
#undef INCLUDE_UNIXSIO
#undef INCLUDE_VME2TIMER
#undef INCLUDE_WD33C93_SCSI1
#undef INCLUDE_WD33C93_SCSI2
#undef INCLUDE_WINSIO
#undef INCLUDE_X2212MEM
#undef INCLUDE_Z8036TIMER
#undef INCLUDE_Z8530SIO
#undef INCLUDE_Z8536TIMER
#undef INCLUDE_SCSI_CDROMFS_DEV0
#undef INCLUDE_SCSI_CDROMFS_DEV1
#undef INCLUDE_SMEND
#undef SM_OFF_BOARD
#undef INCLUDE_SM_SEQ_ADDR
#undef INCLUDE_WVNET
#undef INCLUDE_SW_FP_SUPPORT
#undef INCLUDE_DUART_USE_EPIC_CRT_INTR
#undef INCLUDE_E500_WATCHDOG
#undef INCLUDE_EPIC_CRT_INTR
#undef INCLUDE_FLASH
#undef INCLUDE_MEZZ_COM2
#undef INCLUDE_MV_END
#undef INCLUDE_PCI
#undef INCLUDE_PRIMARY_FCC_END
#undef INCLUDE_SCC_SERIAL
#undef INCLUDE_SECONDARY_FCC_END
#undef INCLUDE_SYS_HW_INIT_0
#undef INCLUDE_SYSCLK
#undef INCLUDE_MINIMAL_MOT_TSEC_END
#undef INCLUDE_MOT_FCC_END
#undef INCLUDE_ETHERNET_ADR_SET


/*** PARAMETERS ***/

#undef  COMP_SIO_XON_OPTION
#undef  INCLUDE_CONSTANT_RDY_Q
#define INCLUDE_CONSTANT_RDY_Q
#undef  LOCAL_MEM_AUTOSIZE
#undef  USER_D_CACHE_ENABLE
#define USER_D_CACHE_ENABLE
#undef  USER_D_MMU_ENABLE
#define USER_D_MMU_ENABLE
#undef  USER_I_CACHE_ENABLE
#define USER_I_CACHE_ENABLE
#undef  USER_I_MMU_ENABLE
#define USER_I_MMU_ENABLE
#undef  INCLUDE_CACHE_SUPPORT
#define INCLUDE_CACHE_SUPPORT
#undef  E500_L1_PARITY_RECOVERY
#undef  INCLUDE_L1_IPARITY_HDLR
#undef  INCLUDE_TFFS_BOOTROM_OVERWRITE
#undef  USE_ALT_BOOTLINE
#undef  AUX_CLK_RATE_MAX
#define AUX_CLK_RATE_MAX 32552
#undef  AUX_CLK_RATE_MIN
#define AUX_CLK_RATE_MIN 7
#undef  HOST_NAME_DEFAULT
#define HOST_NAME_DEFAULT "bootHost"
#undef  TARGET_NAME_DEFAULT
#define TARGET_NAME_DEFAULT "vxTarget"
#undef  HOST_USER_DEFAULT
#define HOST_USER_DEFAULT "target"
#undef  HOST_PASSWORD_DEFAULT
#define HOST_PASSWORD_DEFAULT ""
#undef  SCRIPT_DEFAULT
#define SCRIPT_DEFAULT ""
#undef  OTHER_DEFAULT
#define OTHER_DEFAULT ""
#undef  USR_MAX_LINK_HDR
#define USR_MAX_LINK_HDR 16
#undef  ICMP_FLAGS_DFLT
#define ICMP_FLAGS_DFLT (ICMP_NO_MASK_REPLY)
#undef  IP_FLAGS_DFLT
#define IP_FLAGS_DFLT (IP_DO_FORWARDING | IP_DO_REDIRECT | IP_DO_CHECKSUM_SND | IP_DO_CHECKSUM_RCV)
#undef  IP_FRAG_TTL_DFLT
#define IP_FRAG_TTL_DFLT 60
#undef  IP_QLEN_DFLT
#define IP_QLEN_DFLT 50
#undef  IP_TTL_DFLT
#define IP_TTL_DFLT 64
#undef  AMIO_CHECK_DISCRETE
#define AMIO_CHECK_DISCRETE TRUE
#undef  ENV_BOOT_ENV_CREATE
#define ENV_BOOT_ENV_CREATE FALSE
#undef  ENV_VAR_USE_HOOKS
#define ENV_VAR_USE_HOOKS TRUE
#undef  MAMIO_DEV_NAME
#define MAMIO_DEV_NAME "/mamio"
#undef  MAMIO_OPTIONS
#define MAMIO_OPTIONS 0x42
#undef  MAX_NUMBER_OF_ACCU
#define MAX_NUMBER_OF_ACCU 256
#undef  MGR_TASK_STACK_SIZE
#define MGR_TASK_STACK_SIZE 0x3000
#undef  MUX_DEMUX_OPTIONS
#define MUX_DEMUX_OPTIONS 0x2
#undef  PARTITION_OS_TASK_PRIORITY
#define PARTITION_OS_TASK_PRIORITY 100
#undef  PARTITION_OS_TASK_STACK_SIZE
#define PARTITION_OS_TASK_STACK_SIZE 4000
#undef  PARTITION_RESTART_TASK_PRIORITY_OFFSET
#define PARTITION_RESTART_TASK_PRIORITY_OFFSET -2
#undef  PARTITION_RESTART_TASK_STACK_SIZE
#define PARTITION_RESTART_TASK_STACK_SIZE 4000
#undef  PARTITION_SYSCALL_STACK_SIZE
#define PARTITION_SYSCALL_STACK_SIZE 4000
#undef  PAYLOAD_INFO_ADRS
#define PAYLOAD_INFO_ADRS EXC_MSG_ADRS
#undef  PD_DEFAULT_BASE_ADRS
#define PD_DEFAULT_BASE_ADRS 0x60000000
#undef  PD_DEFAULT_HEAP_SIZE
#define PD_DEFAULT_HEAP_SIZE 0x00000800
#undef  PD_DEFAULT_LT_SIZE
#define PD_DEFAULT_LT_SIZE 0x4000
#undef  PD_DEFAULT_OPTIONS
#define PD_DEFAULT_OPTIONS 0x0
#undef  PD_DEFAULT_SIZE
#define PD_DEFAULT_SIZE 0x08000000
#undef  PD_HEAP_GROWTH_INCREMENT
#define PD_HEAP_GROWTH_INCREMENT 0x1000
#undef  PD_MAX_NUMBER_OF_PDS
#define PD_MAX_NUMBER_OF_PDS 64
#undef  PORT_MONITOR_MAX_NB_MSGS
#define PORT_MONITOR_MAX_NB_MSGS 1000
#undef  PORT_MONITOR_MSG_DISCARD
#define PORT_MONITOR_MSG_DISCARD TRUE
#undef  PPS_ACTIVATION_WINDOW
#define PPS_ACTIVATION_WINDOW 20
#undef  SCHED_MAXIMUM_JITTER
#define SCHED_MAXIMUM_JITTER (-1)
#undef  SCHED_VALIDATE_SCHEDULES
#define SCHED_VALIDATE_SCHEDULES FALSE
#undef  SERIALIZED_DEV_IN_NAME
#define SERIALIZED_DEV_IN_NAME "/tyCo/0"
#undef  SERIALIZED_DEV_OPTIONS
#define SERIALIZED_DEV_OPTIONS 0x34
#undef  SERIALIZED_DEV_OUT_NAME
#define SERIALIZED_DEV_OUT_NAME "/tyCo/0"
#undef  SYS_PG_USER_ADRS
#define SYS_PG_USER_ADRS 0xFFFFFFFF
#undef  TIME_MONITOR_ENABLE
#define TIME_MONITOR_ENABLE TRUE
#undef  APEX_PORT_HEADER_MAX_SIZE
#define APEX_PORT_HEADER_MAX_SIZE 72
#undef  APEX_PORT_ALIGN_SIZE
#define APEX_PORT_ALIGN_SIZE 8
#undef  APEX_PORT_DAP_DMA_COPY_REQUIRED
#define APEX_PORT_DAP_DMA_COPY_REQUIRED TRUE
#undef  ADR_SPACE_ALLOC_UNIT
#define ADR_SPACE_ALLOC_UNIT 0x04000000      
#undef  ADR_SPACE_BASE
#define ADR_SPACE_BASE 0x00000000
#undef  ADR_SPACE_SIZE
#define ADR_SPACE_SIZE 0xFFFFFFFF
#undef  ADR_SPACE_SL_ALLOC_UNIT
#define ADR_SPACE_SL_ALLOC_UNIT 0x00400000
#undef  BOOT_LINE_ADRS
#define BOOT_LINE_ADRS ((char *)(LOCAL_MEM_LOCAL_ADRS + BOOT_LINE_OFFSET))
#undef  BOOT_LINE_OFFSET
#define BOOT_LINE_OFFSET 0x4200
#undef  BOOT_LINE_SIZE
#define BOOT_LINE_SIZE 0xFF
#undef  CONSOLE_TTY
#define CONSOLE_TTY 0
#undef  CORE_OS_MEM_POOL_RGN_SIZE
#define CORE_OS_MEM_POOL_RGN_SIZE 0x01000000
#undef  DEFAULT_BOOT_LINE
#define DEFAULT_BOOT_LINE "mottsec(0,0)LUL-THIERRYM-L1:C:/PSC-2.1/vxworks653-2.1/target/proj/wrSbc8560_default/vxWorks/PPC85XXgnu.debug/boot.txt e=147.11.76.158:FFFF0000 h=147.11.76.105 u=target pw=target tn=wrSbc8560-test"
#undef  EXC_MSG_ADRS
#define EXC_MSG_ADRS ((char *)(LOCAL_MEM_LOCAL_ADRS + EXC_MSG_OFFSET))
#undef  EXC_MSG_OFFSET
#define EXC_MSG_OFFSET 0x4300
#undef  EXC_TASK_STACK_SIZE
#define EXC_TASK_STACK_SIZE 8000
#undef  FREE_RAM_ADRS
#define FREE_RAM_ADRS (end)
#undef  INT_LOCK_LEVEL
#define INT_LOCK_LEVEL 0x0
#undef  ISR_STACK_SIZE
#define ISR_STACK_SIZE 5000
#undef  LOCAL_MEM_LOCAL_ADRS
#define LOCAL_MEM_LOCAL_ADRS 0x00000000
#undef  LOCAL_MEM_SIZE
#define LOCAL_MEM_SIZE 0x20000000
#undef  LOG_TASK_STACK_SIZE
#define LOG_TASK_STACK_SIZE 8192
#undef  MEM_ATTR_LIB_DEFAULT_OPTIONS
#define MEM_ATTR_LIB_DEFAULT_OPTIONS MEM_ATTR_USE_HEAP_FOR_RW
#undef  MEM_LITE_MEM_RESERVED_SIZE
#define MEM_LITE_MEM_RESERVED_SIZE 0x0
#undef  MEM_LITE_MEM_RESERVED_ALIGNMENT
#define MEM_LITE_MEM_RESERVED_ALIGNMENT 0x0
#undef  MEM_LITE_RGN_BASE_ADRS
#define MEM_LITE_RGN_BASE_ADRS FREE_RAM_ADRS
#undef  NUM_DRIVERS
#define NUM_DRIVERS 20
#undef  NUM_FILES
#define NUM_FILES 50
#undef  NUM_SELECT
#define NUM_SELECT 50
#undef  NUM_TTY
#define NUM_TTY 2
#undef  NV_BOOT_OFFSET
#define NV_BOOT_OFFSET 0x0
#undef  NV_RAM_SIZE
#define NV_RAM_SIZE 0x2000
#undef  OBJ_LIBRARY_OPTIONS
#define OBJ_LIBRARY_OPTIONS 0x0
#undef  RESERVED
#define RESERVED 0x4400
#undef  RGN_LIB_OPTIONS
#define RGN_LIB_OPTIONS 0
#undef  ROM_WARM_ADRS
#define ROM_WARM_ADRS (ROM_TEXT_ADRS + 0x0008)
#undef  ROOT_STACK_SIZE
#define ROOT_STACK_SIZE 20000
#undef  STACK_SAVE
#define STACK_SAVE 0x1000
#undef  SYS_CLK_RATE
#define SYS_CLK_RATE 60
#undef  SYS_CLK_RATE_MAX
#define SYS_CLK_RATE_MAX 8000
#undef  SYS_CLK_RATE_MIN
#define SYS_CLK_RATE_MIN 1
#undef  TASK_LIBRARY_OPTIONS
#define TASK_LIBRARY_OPTIONS 0x0
#undef  TASK_DEFAULT_OPTIONS
#define TASK_DEFAULT_OPTIONS VX_FP_TASK
#undef  TASK_DEFAULT_STACK_SIZE
#define TASK_DEFAULT_STACK_SIZE 20000
#undef  TASK_EXC_STACK_SIZE
#define TASK_EXC_STACK_SIZE 8192
#undef  TASK_EXTRA_GUARD_PAGES
#define TASK_EXTRA_GUARD_PAGES 0
#undef  TYLIB_XOFF_PERCENT
#define TYLIB_XOFF_PERCENT 85
#undef  TYLIB_XON_PERCENT
#define TYLIB_XON_PERCENT 80
#undef  TYLIB_WRT_THRESHOLD
#define TYLIB_WRT_THRESHOLD 20
#undef  USER_D_CACHE_MODE
#define USER_D_CACHE_MODE DCACHE_MODE
#undef  USER_I_CACHE_MODE
#define USER_I_CACHE_MODE ICACHE_MODE
#undef  USER_MMU_CACHE_DEFAULT
#define USER_MMU_CACHE_DEFAULT USER_D_CACHE_MODE
#undef  USER_RESERVED_MEM
#define USER_RESERVED_MEM (0)
#undef  VEC_BASE_ADRS
#define VEC_BASE_ADRS ((char *) 0x0 )
#undef  VM_PAGE_SIZE
#define VM_PAGE_SIZE 0x1000
#undef  WIND_JOBS_MAX
#define WIND_JOBS_MAX 64
#undef  WDB_TTY_CHANNEL
#define WDB_TTY_CHANNEL 2
#undef  ATEXIT_NUMBER_OF_FUNCS
#define ATEXIT_NUMBER_OF_FUNCS 32
#undef  MUX_MAX_BINDS
#define MUX_MAX_BINDS 16
#undef  NUM_NET_MBLKS
#define NUM_NET_MBLKS 400
#undef  NUM_CL_BLKS
#define NUM_CL_BLKS (NUM_64 + NUM_128 + NUM_256 + NUM_512 + NUM_1024 + NUM_2048)
#undef  NUM_64
#define NUM_64 100
#undef  NUM_128
#define NUM_128 100
#undef  NUM_256
#define NUM_256 40
#undef  NUM_512
#define NUM_512 40
#undef  NUM_1024
#define NUM_1024 25
#undef  NUM_2048
#define NUM_2048 25
#undef  NUM_SYS_MBLKS
#define NUM_SYS_MBLKS (2 * NUM_SYS_CL_BLKS)
#undef  NUM_SYS_CL_BLKS
#define NUM_SYS_CL_BLKS 140
#undef  NUM_SYS_64
#define NUM_SYS_64 40
#undef  NUM_SYS_128
#define NUM_SYS_128 40
#undef  NUM_SYS_256
#define NUM_SYS_256 40
#undef  NUM_SYS_512
#define NUM_SYS_512 20
#undef  IP_MAX_UNITS
#define IP_MAX_UNITS 4
#undef  RSH_STDERR_SETUP_TIMEOUT
#define RSH_STDERR_SETUP_TIMEOUT -1
#undef  TCP_CON_TIMEO_DFLT
#define TCP_CON_TIMEO_DFLT 150
#undef  TCP_FLAGS_DFLT
#define TCP_FLAGS_DFLT (TCP_DO_RFC1323)
#undef  TCP_IDLE_TIMEO_DFLT
#define TCP_IDLE_TIMEO_DFLT 14400
#undef  TCP_MAX_PROBE_DFLT
#define TCP_MAX_PROBE_DFLT 8
#undef  TCP_MSS_DFLT
#define TCP_MSS_DFLT 512
#undef  TCP_RCV_SIZE_DFLT
#define TCP_RCV_SIZE_DFLT 8192
#undef  TCP_REXMT_THLD_DFLT
#define TCP_REXMT_THLD_DFLT 3
#undef  TCP_RND_TRIP_DFLT
#define TCP_RND_TRIP_DFLT 3
#undef  TCP_SND_SIZE_DFLT
#define TCP_SND_SIZE_DFLT 8192
#undef  TCP_RAND_FUNC
#define TCP_RAND_FUNC (FUNCPTR)random
#undef  UDP_FLAGS_DFLT
#define UDP_FLAGS_DFLT (UDP_DO_CKSUM_SND | UDP_DO_CKSUM_RCV)
#undef  UDP_RCV_SIZE_DFLT
#define UDP_RCV_SIZE_DFLT 41600
#undef  UDP_SND_SIZE_DFLT
#define UDP_SND_SIZE_DFLT 9216
#undef  USER_APPL_INIT
#define USER_APPL_INIT /* Add your function call here */
#undef  REPORTING_TASK_PRIORITY
#define REPORTING_TASK_PRIORITY 100
#undef  WDB_BP_MAX
#define WDB_BP_MAX 50
#undef  WDB_COMM_PORT
#define WDB_COMM_PORT 0x4321
#undef  WDB_GOPHER_TAPE_LEN
#define WDB_GOPHER_TAPE_LEN 4096
#undef  WDB_GOPHER_TAPE_NB
#define WDB_GOPHER_TAPE_NB 10
#undef  WDB_MAX_RESTARTS
#define WDB_MAX_RESTARTS 5
#undef  WDB_NUM_USR_SVC
#define WDB_NUM_USR_SVC 10
#undef  WDB_POOL_SIZE
#define WDB_POOL_SIZE 0x1000
#undef  WDB_RESTART_TIME
#define WDB_RESTART_TIME 5
#undef  WDB_SPAWN_OPTS
#define WDB_SPAWN_OPTS VX_FP_TASK
#undef  WDB_SPAWN_PRI
#define WDB_SPAWN_PRI 100
#undef  WDB_SPAWN_STACK_SIZE
#define WDB_SPAWN_STACK_SIZE 0x5000
#undef  WDB_STACK_SIZE
#define WDB_STACK_SIZE 0x2000
#undef  WDB_TASK_OPTIONS
#define WDB_TASK_OPTIONS VX_UNBREAKABLE | VX_FP_TASK
#undef  WDB_TASK_PRIORITY
#define WDB_TASK_PRIORITY 3
#undef  WDB_VAL_SYNC_TIMEOUT
#define WDB_VAL_SYNC_TIMEOUT 0
#undef  WDB_END_MTU
#define WDB_END_MTU 1500
#undef  WDB_END_DEVICE_NAME
#define WDB_END_DEVICE_NAME NULL
#undef  WDB_END_DEVICE_UNIT
#define WDB_END_DEVICE_UNIT 0
#undef  MII_MONITOR_DELAY
#define MII_MONITOR_DELAY 0x2
#undef  PPC_FPSCR
#define PPC_FPSCR 0x000000d0      /* enable VE, ZE, and OE bits */
#undef  DATA_CACHE_FLUSH_ALL_READ_ADDRESS
#define DATA_CACHE_FLUSH_ALL_READ_ADDRESS RAM_LOW_ADRS
#undef  USE_MMU_HASH_TABLE_ONLY
#define USE_MMU_HASH_TABLE_ONLY FALSE
#undef  ROMSTART_CACHE_ENABLE
#define ROMSTART_CACHE_ENABLE 1	
#undef  ALT_BOOT_LINE
#define ALT_BOOT_LINE "motfcc(0,0)host:/target/config/wrSbc8560/vxWorks h=90.0.0.3 e=90.0.0.50 u=vxworks"
#undef  BSP_REV
#define BSP_REV "/1" 
#undef  BSP_VER_1_1
#define BSP_VER_1_1 1
#undef  BSP_VER_1_2
#define BSP_VER_1_2 1
#undef  BSP_VERSION
#define BSP_VERSION "1.3" 
#undef  CACHE_LIBRARY_MODE
#define CACHE_LIBRARY_MODE  (CACHE_COPYBACK | CACHE_SNOOP_ENABLE)
#undef  CAM_DRAM_CACHE_MODE
#define CAM_DRAM_CACHE_MODE  (0)
#undef  CPU_PCI_IO_ADRS
#define CPU_PCI_IO_ADRS  PCI_IO_ADRS
#undef  CPU_PCI_IO_SIZE
#define CPU_PCI_IO_SIZE  PCI_IO_SIZE
#undef  CPU_PCI_MEMIO_ADRS
#define CPU_PCI_MEMIO_ADRS  PCI_MEMIO_ADRS
#undef  CPU_PCI_MEMIO_SIZE
#define CPU_PCI_MEMIO_SIZE  PCI_MEMIO_SIZE
#undef  CPU_PCI_MEM_ADRS
#define CPU_PCI_MEM_ADRS  PCI_MEM_ADRS
#undef  CPU_PCI_MEM_SIZE
#define CPU_PCI_MEM_SIZE  PCI_MEM_SIZE
#undef  DCACHE_MODE
#define DCACHE_MODE  (CACHE_COPYBACK)
#undef  ENET_DEFAULT
#define ENET_DEFAULT 0x1ea00000
#undef  FLASH_SEGMENT_SIZE
#define FLASH_SEGMENT_SIZE  0
#undef  FREQ_100_MHZ
#define FREQ_100_MHZ 99999999
#undef  FREQ_133_MHZ
#define FREQ_133_MHZ 133333333
#undef  FREQ_266_MHZ
#define FREQ_266_MHZ 266666666
#undef  FREQ_33_MHZ
#define FREQ_33_MHZ 33333333
#undef  FREQ_66_MHZ
#define FREQ_66_MHZ 66666666
#undef  ICACHE_MODE
#define ICACHE_MODE  (CACHE_COPYBACK)
#undef  L2_CACHE_SIZE
#define L2_CACHE_SIZE L2SIZ_128KB
#undef  L2_SRAM_SIZE
#define L2_SRAM_SIZE L2SIZ_128KB
#undef  L2SRAM_ADDR
#define L2SRAM_ADDR (0x7FFC0000)
#undef  L2SRAM_WINDOW_SIZE
#define L2SRAM_WINDOW_SIZE (0x00040000)
#undef  LOCAL_MEM_END_ADRS
#define LOCAL_MEM_END_ADRS (LOCAL_MEM_LOCAL_ADRS+LOCAL_MEM_SIZE)
#undef  NV_MAC_ADRS_OFFSET
#define NV_MAC_ADRS_OFFSET 0x200
#undef  NV_RAM_ADRS
#define NV_RAM_ADRS 0x28b00000
#undef  NV_RAM_INTRVL
#define NV_RAM_INTRVL 1
#undef  OSCILLATOR_FREQ
#define OSCILLATOR_FREQ FREQ_66_MHZ
#undef  PCI_BRIDGE_PIMMR_BASE_ADRS
#define PCI_BRIDGE_PIMMR_BASE_ADRS  0x40000000
#undef  PCI_CFG_TYPE
#define PCI_CFG_TYPE  PCI_CFG_AUTO
#undef  PCI_IO_ADRS
#define PCI_IO_ADRS  0xB0000000
#undef  PCI_IO_SIZE
#define PCI_IO_SIZE  0x01000000
#undef  PCI_LOCAL_MEM_BUS
#define PCI_LOCAL_MEM_BUS  0x00000000
#undef  PCI_LOCAL_MEM_SIZE
#define PCI_LOCAL_MEM_SIZE  PCI_MSTR_MEM_SIZE
#undef  PCI_LOCAL_MEM_SIZE_MASK
#define PCI_LOCAL_MEM_SIZE_MASK  PCI_ATTR_WS_128M
#undef  PCI_MEMIO_ADRS
#define PCI_MEMIO_ADRS  0xA0000000
#undef  PCI_MEMIO_SIZE
#define PCI_MEMIO_SIZE  0x01000000
#undef  PCI_MEMIO_SIZE_MASK
#define PCI_MEMIO_SIZE_MASK PCI_ATTR_WS_16M
#undef  PCI_MEM_ADRS
#define PCI_MEM_ADRS  0x90000000
#undef  PCI_MEM_SIZE
#define PCI_MEM_SIZE  0x01000000
#undef  PCI_MEM_SIZE_MASK
#define PCI_MEM_SIZE_MASK PCI_ATTR_WS_16M
#undef  PLAT_FREQ_DEFAULT
#define PLAT_FREQ_DEFAULT (OSCILLATOR_FREQ * 3)
#undef  DEFAULT_POWER_MGT_MODE
#define DEFAULT_POWER_MGT_MODE (VX_POWER_MODE_DISABLE)
#undef  RAM_HIGH_ADRS
#define RAM_HIGH_ADRS 0x00e00000
#undef  RAM_LOW_ADRS
#define RAM_LOW_ADRS 0x00010000
#undef  RAM_PAYLOAD_ADRS
#define RAM_PAYLOAD_ADRS (LOCAL_MEM_END_ADRS - RAM_PAYLOAD_SIZE)
#undef  RAM_PAYLOAD_SIZE
#define RAM_PAYLOAD_SIZE  0
#undef  ROM_BASE_ADRS
#define ROM_BASE_ADRS 0xfff00000
#undef  ROM_SIZE
#define ROM_SIZE 0x00100000
#undef  ROM_TEXT_ADRS
#define ROM_TEXT_ADRS 0xfff00000
#undef  TLB_CACHE_MODE
#define TLB_CACHE_MODE  (VM_STATE_CACHEABLE)
#undef  USR_MAC3a
#define USR_MAC3a 0xb4
#undef  USR_MAC3b
#define USR_MAC3b 0xb5
#undef  USR_MAC3c
#define USR_MAC3c 0xb6
#undef  USR_MAC3d
#define USR_MAC3d 0xb7
#undef  USR_MAC4
#define USR_MAC4 0x2e
#undef  USR_MAC5
#define USR_MAC5 0x3f
#undef  WR_MAC0
#define WR_MAC0 0x00
#undef  WR_MAC1
#define WR_MAC1 0xa0
#undef  WR_MAC2
#define WR_MAC2 0x1e

#endif /* INCprjParamsh */
