name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Run CMake and build'
      run: |
        mkdir -p build
        cd build && cmake ..
        make -j`nproc`
    - name: Run tests
      run: cd build && ctest -V -j`nproc`
